# Generated by Django 3.2.8 on 2021-10-29 13:39

from django.db import migrations
import librarybackend.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_create_user_model'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', librarybackend.base.models.UserManager()),
            ],
        ),
    ]
