version: '3.8'

services:
    db:
        image: 'postgres:9.4'
        container_name: 'librarybackend'
        ports:
            - 5434:5432
        tty: true
        volumes:
            - .data/.pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=librarydb
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=localhost
